/// Flutter icons Instag
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Instag
///      fonts:
///       - asset: fonts/Instag.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Instag {
  Instag._();

  static const _kFontFam = 'Instag';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mentions = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifiations = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reel = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reels = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
